python3_test:
  image: python:3
  script:
    - apt-get update -qy
    - apt-get install -qy python3-dev python3-pip
    - python3 --version
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install .
    - python3 tests/test_baysian_compressive.py
    - ls
    - python3 tests/test_ce_calculator.py
    - ls
    - python3 tests/test_cebulk.py
    - python3 tests/test_column_sparse_matrix.py
    - python3 tests/test_conc.py
    - python3 tests/test_corr_func.py
    - python3 tests/test_formula_unit.py
    - python3 tests/test_ga_fit.py
    - python3 tests/test_orthonormal_basis.py
    - python3 tests/test_regression.py
    - python3 tests/test_supercell_factor.py
    - python3 tests/test_templates.py
    - python3 tests/test_trans_matrix_constructor.py

