image: python:latest

before_script:
  - python3 --version

stages:
  - Static Analysis
  - Code Test
  - Deploy

flake8:
  stage: Static Analysis
  script:
    - python3 -m pip install flake8
    - flake8 clease/

pylint:
  stage: Static Analysis
  script:
    - python3 -m pip install pylint
    - pylint --disable=all --enable=dangerous-default-value clease/

# mypy:
#   stage: Static Analysis
#   allow_failure: true
#   script:
#     - pip install mypy
#     - pwd
#     - python3 -m mypy clease/

pytest:default:
  stage: Code Test
  coverage: '/TOTAL\s+.*( \d+\%)/'
  script:
    - pwd
    - python3 -m pip install coverage
    - python3 -m pip install .[test]
    - coverage run --omit='tests/*' -m pytest tests/
    - coverage report

doctest:
  stage: Code Test
  script:
    - python3 -m pip install .[doc]
    - apt-get update -qy
    - apt-get install -qy xvfb
    - cd doc
    - make doctest SPHINXOPTS="-W"

pages:
  stage: Deploy
  script:
    - python3 -m pip install .[doc]
    - cd doc
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

python3_test_slow:
  stage: Code Test
  coverage: '/TOTAL\s+.*( \d+\%)/'
  script:
    - python3 --version
    - python3 -m pip install .[test]
    - pytest --runslow tests/
  when: manual

.pytest_template: &pytest_definition
  stage: Code Test
  script:
    - python3 -m pip install .[test]
    - python3 -m pytest tests/

# Some optional tests for older python versions
pytest:py36:
  image: python:3.6
  <<: *pytest_definition
  when: manual

pytest:py37:
  image: python:3.7
  <<: *pytest_definition
  when: manual

pytest:py38:
  image: python:3.8
  <<: *pytest_definition
  when: manual
