image: ubuntu:14.04

before_script:
    - apt-get update -qy
    - apt-get install -qy python-dev python-pip

python3_test:
  script:
    - python --version
    - pip install -r requirements.txt
    - pip install .
    - python -m unittest discover tests/

