python3_test:
  image: python:3
  script:
    - apt-get update -qy
    - apt-get install -qy python3-dev python3-pip
    - python3 --version
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install .
    - ldd clease_cxx.so
    - python3 -m unittest discover tests/

