image: ubuntu:16.04

before_script:
    - apt-get update -qy
    - apt-get install -qy python3-dev python3-pip

python3_test:
  script:
    - python3 --version
    - pip3 install -r requirements.txt
    - pip3 install .
    - python3 -m unittest discover tests/

