python3_test:
  image: python:3
  script:
    - apt-get update -qy
    - apt-get install -qy python3-dev python3-pip
    - python3 --version
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install .
    - python3 -m unittest discover tests/

gui_test:
  image: python:3
  script:
    - apt-get update -qy
    - apt-get install -qy python3-dev python3-pip
    - apt-get install -qy xvfb
    - python3 --version
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install kivy
    - python3 -m pip install kivy-garden
    - garden install matplotlib
    - python3 -m pip install .
    - export KIVY_GL_BACKEND=mock
    - xvfb-run --server-args="-screen 0 1280x720x24 -ac +extension GLX" python3 tests/gui/test_navigation_menu.py