image: python:3-slim

python3_test:
  script:
    - apt-get update
    - apt-get install g++
    - apt-get install python-dev
    - python --version
    - pip install -r requirements.txt
    - pip install .
    - python -m unittest discover tests/

