image: python:3.11

before_script:
  - python3 --version
  - python3 -m pip install tox

stages:
  - Static Analysis
  - Code Test
  - Deploy

code-style:
  stage: Static Analysis
  script:
    - tox -e style

pylint:
  stage: Static Analysis
  image: python:3.10  # Pylint on 3.11 seems to be broken
  script:
    - tox -e pylint

# mypy:
#   stage: Static Analysis
#   allow_failure: true
#   script:
#     - pip install mypy
#     - pwd
#     - python3 -m mypy clease/

pytest:default:
  stage: Code Test
  coverage: '/TOTAL\s+.*( \d+\%)/'
  script:
    - pwd
    - tox -e cov
  artifacts:
    paths:
      - .coverage
    expire_in: 2 weeks

doctest:
  stage: Code Test
  script:
    - python3 -m pip install .[doc]
    - apt-get update -qy
    - apt-get install -qy xvfb
    - cd doc
    - make doctest SPHINXOPTS="-W"

.test_template: &manual_test
  stage: Code Test
  when: manual

python3_test_slow:
  script:
    - tox -e current -- --runslow --durations=30 tests/
  <<: *manual_test

# Some optional tests for older python versions
pytest:py37:
  image: python:3.7
  <<: *manual_test
  script:
    - tox -e py37

pytest:py38:
  image: python:3.8
  <<: *manual_test
  script:
    - tox -e py38

pytest:py39:
  image: python:3.9
  <<: *manual_test
  script:
    - tox -e py39

pytest:py310:
  image: python:3.10
  <<: *manual_test
  script:
    - tox -e py310

# CI to test CLEASE against the current ASE master.
pytest:ase_master:
  <<: *manual_test
  script:
    - tox -e ase

# Build as many linux wheels as we can. Only to be triggered manually.
# This takes a while, and performs no uploads to PyPI, only to gitlab.
linux_wheels:
  # Based on https://cibuildwheel.readthedocs.io/en/stable/setup/#gitlab-ci
  stage: Deploy
  when: manual
  image: python:3.8
  # make a docker daemon available for cibuildwheel to use
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
    # Only build CPython 3.7-3.11, no PyPy, only manylinux
    CIBW_BUILD: cp{37,38,39,310,311}-manylinux*
    # Add the -fopenmp flag for wheel building.
    CIBW_ENVIRONMENT_LINUX: CLEASE_OMP='-fopenmp'
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: ${CI_PYPI_TOKEN}
  script:
    - curl -sSL https://get.docker.com/ | sh
    - python -m pip install cibuildwheel==2.11.2 twine
    - cibuildwheel --output-dir wheelhouse
    - twine check wheelhouse/*
    - twine upload wheelhouse/*
  artifacts:
    paths:
      - wheelhouse/
    expire_in: 2 weeks
  tags:
    # CLEASER chokes on this job, so make it target only non-cleaser tags
    # (due to not being able to do DinD, security reasons)
    - gitlab-org-docker

pypi:
  stage: Deploy
  cache: {}
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: ${CI_PYPI_TOKEN}
  script:
    - pip install pyclean>=2.0.0 twine build
    - make publish
  # https://stackoverflow.com/a/52807912
  # only allow on tags on master
  only:
    - tags
  except:
    - branches
  # Safety guard that it's a tag + manual trigger.
  when: manual
