image: python:latest

before_script:
  - python3 --version

stages:
  - Static Analysis
  - Code Test
  - Deploy

flake8:
  stage: Static Analysis
  script:
    - python3 -m pip install flake8
    - flake8 clease/

pylint:
  stage: Static Analysis
  script:
    - python3 -m pip install pylint
    - pylint --disable=all --enable=dangerous-default-value clease/

# mypy:
#   stage: Static Analysis
#   allow_failure: true
#   script:
#     - pip install mypy
#     - pwd
#     - python3 -m mypy clease/

pytest:default:
  stage: Code Test
  coverage: '/TOTAL\s+.*( \d+\%)/'
  script:
    - pwd
    - python3 -m pip install coverage
    - python3 -m pip install .[test]
    - coverage run --omit='tests/*' -m pytest tests/
    - coverage report

gui_test:
  stage: Code Test
  image: python:3.7 # Requies at most python 3.7
  coverage: '/TOTAL\s+.*( \d+\%)/'
  script:
    - apt-get update -qy
    - apt-get install -qy xvfb libmtdev1
    - python3 -m pip install coverage
    #    - clease gui --setup
    - python3 -m pip install .[gui]
    - export KIVY_GL_BACKEND=mock
    - xvfb-run --server-args="-screen 0 1280x720x24 -ac +extension GLX" python3 gui_tests/test_gui.py
    - xvfb-run --server-args="-screen 0 1280x720x24 -ac +extension GLX" coverage run --include='*/clease/gui/*' -m unittest discover gui_tests/
    - coverage report

doctest:
  stage: Code Test
  script:
    - python3 -m pip install .[doc]
    - apt-get update -qy
    - apt-get install -qy xvfb
    - cd doc
    - make doctest

pages:
  stage: Deploy
  script:
    - python3 -m pip install .[doc]
    - cd doc
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

python3_test_slow:
  stage: Code Test
  coverage: '/TOTAL\s+.*( \d+\%)/'
  script:
    - python3 --version
    - python3 -m pip install .[test]
    - pytest --runslow tests/
  when: manual

.pytest_template: &pytest_definition
  stage: Code Test
  script:
    - python3 -m pip install .[test]
    - python3 -m pytest tests/

# Some optional tests for older python versions
pytest:py36:
  image: python:3.6
  <<: *pytest_definition
  when: manual

pytest:py37:
  image: python:3.7
  <<: *pytest_definition
  when: manual

pytest:py38:
  image: python:3.8
  <<: *pytest_definition
  when: manual
