image: ubuntu:latest

before_script:
    - apt-get update -qy
    - apt-get install -qy python3-dev python3-pip

python3_test:
  script:
    - python3 --version
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install .
    - python3 -m unittest discover tests/

