image: python:3.7

before_script:
  - pip install .
  - python3 --version

stages:
  - Static Analysis
  - Code Test
  - Deploy

flake8:
  stage: Static Analysis
  script:
    - pip install flake8
    - flake8 clease/

pylint:
  stage: Static Analysis
  script:
    - pip install pylint
    - pylint --disable=all --enable=dangerous-default-value clease/

# mypy:
#   stage: Static Analysis
#   allow_failure: true
#   script:
#     - pip install mypy
#     - pwd
#     - python3 -m mypy clease/

pytests:
  stage: Code Test
  coverage: '/TOTAL\s+.*( \d+\%)/'
  script:
    - pwd
    - pip install coverage
    - coverage run --omit='tests/*' -m pytest tests/
    - coverage report

gui_test:
  stage: Code Test
  coverage: '/TOTAL\s+.*( \d+\%)/'
  script:
    - apt-get update -qy
    - apt-get install -qy xvfb libmtdev1
    - pip install coverage
#    - clease gui --setup
    - pip install .[gui]
    - export KIVY_GL_BACKEND=mock
    - xvfb-run --server-args="-screen 0 1280x720x24 -ac +extension GLX" python3 gui_tests/test_gui.py
    - xvfb-run --server-args="-screen 0 1280x720x24 -ac +extension GLX" coverage run --include='*/clease/gui/*' -m unittest discover gui_tests/
    - coverage report

doctest:
  stage: Code Test
  script:
    - apt-get update -qy
    - apt-get install -qy xvfb
    - python3 -m pip install sphinx
    - python3 -m pip install sphinx_rtd_theme
    - cd doc
    - make doctest

pages:
  stage: Deploy
  script:
    - python3 -m pip install sphinx
    - python3 -m pip install sphinx_rtd_theme
    - cd doc
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

python3_test_slow:
  stage: Code Test
  image: python:3.7
  coverage: '/TOTAL\s+.*( \d+\%)/'
  script:
    - python3 --version
    - python3 -m pip install .
    - pytest --runslow tests/
  when: manual
