# yet another python formatter
repos:
  - repo: local
    hooks:
      # yapf = yet another python formatter
      - id: yapf
        name: yapf
        entry: yapf
        language: system
        types: [python]
        args: ["-i"]
        exclude: &exclude_files >
          (?x)(
            ^doc/|
            ^tests/
          )

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: *exclude_files

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: check-yaml
