[project]
requires-python = ">=3.7"

[build-system]
requires = ["setuptools", "wheel", "Cython", "numpy"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ["py37"]
