[build-system]
# setuptools 61.0 broke, see !488
requires = ["setuptools >=58, !=61.0", "wheel", "Cython", "numpy"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ["py37"]
