image:
  - Visual Studio 2019 # Windows
  - macOS
# We skip running an ubuntu image, since we already test linux on the GitLab CI

install:
  # Windows only
  - cmd: "SET PYTHON=C:\\Python38-x64"
  - cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Nix only
  - sh: "source ~/venv3.8/bin/activate"
  # Common Python install commands
  - "python --version"
  - "python -m pip install build tox"

build: off

test_script:
  - "tox -e current"

after_test:
  # Build wheels
  - "python -m build --wheel"

artifacts:
  # Built wheels are in the dist directory
  - path: dist/*
